name: MahatmaHouse
favicon: null
layout_spectrum: 0.838674157159403
typography_spectrum: 0.07033174973912537
title: Mahatma House
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f8fa'
    - '#1b87c8'
    - '#0c2021'
    - '#a7d0f0'
    - '#93b32c'
  brandStrength: 1
  lightness: 0.9375
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
